# Generated by Django 3.2.8 on 2021-10-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mypost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('imagepost', models.ImageField(blank=True, null=True, upload_to='')),
                ('feedpost', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='imagepost',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
