# Generated by Django 3.2.8 on 2021-11-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_auto_20211029_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackMD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('imagepost', models.ImageField(upload_to='images/')),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='feedback',
            new_name='mypostMD',
        ),
        migrations.RenameModel(
            old_name='register',
            new_name='registerMD',
        ),
        migrations.DeleteModel(
            name='mypost',
        ),
        migrations.RenameField(
            model_name='mypostmd',
            old_name='feed',
            new_name='feedpost',
        ),
        migrations.RenameField(
            model_name='mypostmd',
            old_name='name',
            new_name='tittle',
        ),
    ]
