# Generated by Django 3.2.8 on 2021-11-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0005_feedbackmd_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackmd',
            old_name='uname',
            new_name='tittle',
        ),
    ]
